### ISSUE TITLE
Parallelization schemes

### ISSUE THREAD

**Issue by Jerry-Ma** [toltec-astro/citlali#3]
The parallelization will happen in multiple layers. We need to plan our architecture to accommodate such needs.

** Timestream Parallelization **

There are a number of ways that we can parallelize the highest data-rate stage of the pipeline.  This stage, which I’ll call Stage 1, is responsible for the first stage of despiking, high and low-pass filtering, decimation, calibration and conversion from I/Q to power, extinction correction, and any other process that does is done on individual detectors and does not require information from other detectors.   We need a group to think through the different parallelization ideas and choose the one that seems best suited to our hardware architecture.

**Comment by mmccrackan** [comment]
Parallelization schemes have largely been settled on outside of minor changes.
