### ISSUE TITLE
Data container choice

### ISSUE THREAD

**Issue by Jerry-Ma** [toltec-astro/citlali#4]
- Eigen

    * http://eigen.tuxfamily.org/index.php?title=Main_Page

    * There is "unsupported" functionalities available: https://eigen.tuxfamily.org/dox/unsupported/ 
    * https://eigen.tuxfamily.org/dox/UserManual_UnderstandingEigen.html this seems to give a quite concise summary of the value of Eigen.

- xtensor 

     * https://xtensor.readthedocs.io/en/latest/
     * has similar functionalities with Eigen.
Test to run to evaluate these options:

ffw, sparse/dense matrix, eigen value, ...

**Comment by mmccrackan** [comment]
Went with Eigen.
