### ISSUE TITLE
install instructions: missing boost dependency 

### ISSUE THREAD

**Issue by rguter** [toltec-astro/citlali#7]
Not sure if this is universal, but in following the install instructions as written on my laptop (Pop_OS 20.04), I needed to install boost as a dependency (e.g. libboost-all-dev).  Suggest adding it to the list of dependency packages to install for ubuntu 20.04 instructions, just in case it isn't present on a given system.

**Comment by Jerry-Ma** [comment]
Thanks for reporting. The boost dependency is something that we wanted to remove. I guess Michael @mmccrackan could chime in here and see how we can get rid of it.

In the meantime, I'll update the readme to include boost as one of the dependence until we fix it.

**Comment by mmccrackan** [comment]
I use the boost libraries in order to get the random numbers for the noise maps, as the random generator in Eigen is not thread-safe to my knowledge, so it would be good to keep at least boost::random in citlali.

**Comment by Jerry-Ma** [comment]
OK. I wanted to get rid of boost just because it seems to be too heavy (just my opinion). I did a bit searching and found this random generator that may also fit out need.

https://www.numbercrunch.de/trng/

**Comment by mmccrackan** [comment]
I'll see about adding that instead.  I just remembered that I also use boost for the Bessel functions in the lowpass filter.  I guess we could use gsl for that, though I imagine that gsl is about the same as boost in terms of scale.

**Comment by Jerry-Ma** [comment]
C++17 has some built in math function. I am not sure if the function we need is included:
https://en.cppreference.com/w/cpp/numeric/special_functions

**Comment by mmccrackan** [comment]
I forget why I didn't use these before, as I know I looked at them, but I think these will work for our purposes.  I'll go ahead and switch away from boost for both the random numbers and for the functions.
